version: "3.9"
services:
  mongo:
    image: "mongo:4.4.5"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data/bla:/var/lib/mongodb/data
      - ./mongo/bootstrap_user.js:/docker-entrypoint-initdb.d/bootstrap_user.js
  web:
    build: ./api_service
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./api_service:/api_service
    ports:
      - 3000:3000
    depends_on:
      - mongo
  worker:
    build: ./api_service
    command: rake jobs:work
    volumes:
      - ./api_service:/api_service
    tty: true
    depends_on:
      - mongo
