version: "3.9"
services:
  mongo-service:
    image: "mongo:4.4.5"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb:/var/lib/mongodb/data"
  web:
    build: ./api_service
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./api_service:/api_service
    ports:
      - "3000:3000"
    depends_on:
      - mongo-service
