development:
  clients:
    default:
      database: api_service_development
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
        user: admin
        password: password
test:
  clients:
    default:
      database: api_service_test
      hosts:
        - mongo:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
        user: admin
        password: password
